### ISSUE TITLE
Adding new Items is not possible if there are less then two Items in the List 

### ISSUE THREAD

**Issue by Tag365** [Tag365/wheel-of-fortune-webapp#1]

**Comment by Gwynbleiid** [comment]
It's possible to add item if there are less than 2 items in the list but by pressing _enter_ and not clicking the _submit_ button

**Comment by Gwynbleiid** [comment]
Just wanted to point that using _Enter_ or the _Submit button_ do not have the same behavior PepeHands no bully please
